version: "3"

services:
  gethnode:
    container_name: gethnode
    build: ./gethnode
    working_dir: /root
    command: /usr/local/bin/geth --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcapi "db,eth,net,web3"
    volumes:
      - ./counteiner_data/geth:/root/.callisto
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    networks:
      - front
#    depends_on:
#      - db
#    links:
#      - db

  db:
    build: mysql/
    container_name: "db"
    environment:
      MYSQL_DATABASE: 'clo_statistic'
      MYSQL_USER: 'clo_statistic'
      MYSQL_PASSWORD: 'clo_statistic'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - front
    ports:
      - "3306:3306"
#    volumes:
#      - ./counteiner_data/log:/var/log/mysql



  web:
    build: web/
    container_name: "web"
#    command: python /code/manage.py migrate --noinput && python manage.py collectstatic && python /code/manage.py runserver 0.0.0.0:8000
#    command: ./docker-entrypoint.sh
    entrypoint: /code/docker-entrypoint.sh
    volumes:
      - ./web/code/:/code
    ports:
      - 8000:8000
#    links:
#      - db
#      - gethnode
    depends_on:
      - db
      - gethnode
    networks:
      - front



networks:
  front: