version: "3"

services:
  gethnode:
    container_name: gethnode
    build: ./gethnode
    working_dir: /root
    command: /usr/local/bin/geth --cache 2048 --syncmode fast --rpc --rpcaddr 0.0.0.0 --rpcport 8545 -rpcapi="db,eth,net,web3,personal,admin,debug" --rpccorsdomain="" --rpcvhosts "*" --wsaddr 0.0.0.0 --wsport 8546 --wsapi="db,eth,net,web3,personal"
#    command: /usr/local/bin/geth --cache 2048 --syncmode full --gcmode archive --rpc --rpcaddr 0.0.0.0 --rpcport 8545 -rpcapi="db,eth,net,web3,personal,admin,debug" --rpccorsdomain="" --rpcvhosts "*" --wsaddr 0.0.0.0 --wsport 8546 --wsapi="db,eth,net,web3,personal"
    volumes:
      - ./counteiner_data/geth:/root/.callisto
    networks:
      - front
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"

  db:
    build: mysql/
    container_name: "db"
    environment:
      MYSQL_DATABASE: 'clo_statistic'
      MYSQL_USER: 'clo_statistic'
      MYSQL_PASSWORD: 'clo_statistic'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./counteiner_data/mysqldir:/var/lib/mysql/:rw
    networks:
      - front
    ports:
      - "3311:3306"

  web:
    build: web/
    container_name: "web"
    entrypoint: /code/docker-entrypoint.sh
    volumes:
      - ./web/code/:/code
    ports:
      - 8000:8000
    depends_on:
      - db
#      - gethnode
    networks:
      - front

networks:
  front: