# Generated by Django 2.2 on 2019-04-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_hash', models.CharField(max_length=256)),
                ('addr_from', models.CharField(max_length=256)),
                ('addr_to', models.CharField(max_length=256)),
                ('input_date', models.CharField(max_length=256)),
                ('extraData', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockNumber', models.IntegerField()),
                ('transactionIndex', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('blockHash', models.CharField(max_length=256)),
                ('contractAddress', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('tx', models.CharField(max_length=256)),
                ('addr_from', models.CharField(db_index=True, max_length=256)),
                ('addr_to', models.CharField(db_index=True, max_length=256)),
                ('gasUsed', models.IntegerField(blank=True, null=True)),
                ('gas', models.IntegerField(blank=True, null=True)),
                ('gasPrice', models.BigIntegerField(blank=True, null=True)),
                ('input', models.CharField(max_length=256)),
                ('input_text', models.CharField(max_length=256)),
                ('value', models.FloatField(blank=True, null=True)),
                ('timestamp', models.IntegerField(default=0)),
            ],
            options={
                'index_together': {('blockNumber', 'transactionIndex')},
            },
        ),
    ]
