# Generated by Django 2.2 on 2019-04-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogethapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=42)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='addr_from',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='addr_to',
            field=models.CharField(db_index=True, max_length=42),
        ),
    ]
