# Generated by Django 2.2 on 2019-04-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clogethapp', '0002_auto_20190426_0520'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transaction',
            index_together={('blockNumber', 'gasUsed', 'gas', 'value')},
        ),
    ]
