# Generated by Django 2.2 on 2019-04-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogethapp', '0002_auto_20190428_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='addr_from',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='block',
            name='addr_to',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_hash',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='blockHash',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx',
            field=models.CharField(max_length=66),
        ),
    ]
