# Generated by Django 2.2 on 2019-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogethapp', '0003_auto_20190428_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csbalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockNumber', models.IntegerField()),
                ('balance', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(max_length=256)),
            ],
        ),
    ]
