# Generated by Django 2.2 on 2019-04-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogethapp', '0003_auto_20190426_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='addr_from',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='addr_to',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
