# Generated by Django 2.2 on 2019-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogethapp', '0005_account_blocknumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='addr',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='csbalance',
            name='blockNumber',
            field=models.IntegerField(db_index=True),
        ),
    ]
