# Generated by Django 2.2 on 2019-04-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clogethapp', '0006_auto_20190429_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
